app:
  build: .
  ports :
    - "${PORT}:3000"
  volumes:
    - .:/usr/src/app/:rw
    - /usr/src/app/node_modules
  command: npm start
  env_file: .env
  environment:
    APP_PORT: 3000
    NODE_ENV: development
  expose:
    - "3000"
